name: RedisLive CI

on:
  push:
    branches: [ "main" ]

env:
  ## Sets environment variable
  dkr_repo: "sushanto/prv"

jobs:

  build_redis_live:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Redis Live Docker image
      run: |
          export tag="redis-stat"
          docker build . --tag $dkr_repo:$tag
          docker push $dkr_repo:$tag
